#ifndef __ATOMS_H_
#define __ATOMS_H_

#include <xcb/xcb.h>
#include <xcb/xcb_atom.h>

enum {
  NET_WM_WINDOW_TYPE = 0,
  NET_WM_WINDOW_TYPE_NORMAL,
  NET_WM_WINDOW_TYPE_DIALOG,
  NET_WM_WINDOW_TYPE_SPLASH,
  NET_WM_WINDOW_TYPE_DOCK,
  NET_WM_WINDOW_TYPE_DROPDOWN_MENU,
  NET_WM_STATE,
  NET_WM_STATE_MODAL,
  NET_WM_STATE_HIDDEN,
  NET_WM_STRUT_PARTIAL,
  NET_WM_WINDOW_OPACITY,
  NET_WM_NAME,
  NET_CLIENT_LIST,
  NET_WM_DESKTOP,
  NET_CURRENT_DESKTOP,
  NET_NUMBER_OF_DESKTOPS,
  SB_ATOM_MAX
};
xcb_atom_t atoms[SB_ATOM_MAX];
#define SB_MAKE_ATOM_STRING(str)                                               \
  { str, sizeof(str) - 1 }
const struct {
  char *name;
  int len;
} SB_ATOM_STRING[SB_ATOM_MAX] = {
    SB_MAKE_ATOM_STRING("_NET_WM_WINDOW_TYPE"),
    SB_MAKE_ATOM_STRING("_NET_WM_WINDOW_TYPE_NORMAL"),
    SB_MAKE_ATOM_STRING("_NET_WM_WINDOW_TYPE_DIALOG"),
    SB_MAKE_ATOM_STRING("_NET_WM_WINDOW_TYPE_SPLASH"),
    SB_MAKE_ATOM_STRING("_NET_WM_WINDOW_TYPE_DOCK"),
    SB_MAKE_ATOM_STRING("_NET_WM_WINDOW_TYPE_DROPDOWN_MENU"),
    SB_MAKE_ATOM_STRING("_NET_WM_STATE"),
    SB_MAKE_ATOM_STRING("_NET_WM_MODAL"),
    SB_MAKE_ATOM_STRING("_NET_WM_HIDDEN"),
    SB_MAKE_ATOM_STRING("_NET_WM_STRUT_PARTIAL"),
    SB_MAKE_ATOM_STRING("_NET_WM_WINDOW_OPACITY"),
    SB_MAKE_ATOM_STRING("_NET_WM_NAME"),
    SB_MAKE_ATOM_STRING("_NET_CLIENT_LIST"),
    SB_MAKE_ATOM_STRING("_NET_WM_DESKTOP"),
    SB_MAKE_ATOM_STRING("_NET_CURRENT_DESKTOP"),
    SB_MAKE_ATOM_STRING("_NET_NUMBER_OF_DESKTOPS")};
#undef SB_MAKE_ATOM_STRING

#endif // __ATOMS_H_
